name: 'publish'

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: npm ci

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Clean Cargo cache
        run: |
          rm -f src-tauri/Cargo.lock
          rm -rf src-tauri/target

      - name: Create or update Cargo.toml
        run: |
          mkdir -p src-tauri
          cat << EOF > src-tauri/Cargo.toml
          [package]
          name = "sv1"
          version = "0.1.0"
          description = "A Tauri App"
          authors = ["you"]
          license = ""
          repository = ""
          default-run = "sv1"
          edition = "2021"
          rust-version = "1.60"
          build = "build.rs"

          [build-dependencies]
          tauri-build = { version = "2.0.0-rc.13", features = [] }

          [dependencies]
          serde_json = "1.0"
          serde = { version = "1.0", features = ["derive"] }
          tauri = { version = "2.0.0-rc.13" }

          [features]
          custom-protocol = [ "tauri/custom-protocol" ]
          EOF

      - name: Create build.rs
        run: |
          cat << EOF > src-tauri/build.rs
          fn main() {
            tauri_build::build()
          }
          EOF

      # First, let's create a minimal main.rs without the Manager import
      - name: Create main.rs
        run: |
          mkdir -p src-tauri/src
          cat << EOF > src-tauri/src/main.rs
          #![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

          fn main() {
            tauri::Builder::default()
              .run(tauri::generate_context!())
              .expect("error while running tauri application");
          }
          EOF

      - name: Display Cargo.toml contents
        run: cat src-tauri/Cargo.toml

      - name: Verify Tauri config
        run: |
          if [ ! -f "src-tauri/tauri.conf.json" ]; then
            echo "Error: src-tauri/tauri.conf.json not found"
            exit 1
          fi
          cat src-tauri/tauri.conf.json

      - name: Build the project
        run: npm run build

      - name: Build Tauri App
        run: npm run tauri build -- ${{ matrix.args }}

      - name: Install ImageMagick (for ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        run: sudo apt-get install -y imagemagick

      - name: Install ImageMagick (for macOS)
        if: matrix.platform == 'macos-latest'
        run: brew install imagemagick

      - name: Install ImageMagick (for Windows)
        if: matrix.platform == 'windows-latest'
        run: choco install imagemagick.app

      # Create a simpler tauri.conf.json with minimal icon requirements
      - name: Create tauri.conf.json
        run: |
          cat << EOF > src-tauri/tauri.conf.json
          {
            "build": {
              "beforeBuildCommand": "",
              "beforeDevCommand": "",
              "devPath": "../dist",
              "distDir": "../dist"
            },
            "package": {
              "productName": "sv1",
              "version": "0.1.0"
            },
            "tauri": {
              "bundle": {
                "active": true,
                "icon": [
                  "icons/32x32.png"
                ],
                "identifier": "com.tauri.dev"
              },
              "windows": [
                {
                  "fullscreen": false,
                  "height": 600,
                  "resizable": true,
                  "title": "sv1",
                  "width": 800
                }
              ]
            }
          }
          EOF

      # Create a simple icon using a more basic approach
      - name: Create icon
        run: |
          mkdir -p src-tauri/icons
          if [ "${{ matrix.platform }}" = "windows-latest" ]; then
            echo "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAA7AAAAOwBeShxvQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABSdEVYdENvcHlyaWdodABDQzAgUHVibGljIERvbWFpbiBEZWRpY2F0aW9uIGh0dHA6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL3B1YmxpY2RvbWFpbi96ZXJvLzEuMC/G4735AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5AYNDgE3tvKz6QAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAAAUSURBVFiF7cEBAQAAAIIg/6/uSEABAADuBgUAAAEVp4M/AAAAAElFTkSuQmCC" | base64 -d > src-tauri/icons/32x32.png
          else
            echo "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAA7AAAAOwBeShxvQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABSdEVYdENvcHlyaWdodABDQzAgUHVibGljIERvbWFpbiBEZWRpY2F0aW9uIGh0dHA6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL3B1YmxpY2RvbWFpbi96ZXJvLzEuMC/G4735AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5AYNDgE3tvKz6QAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAAAUSURBVFiF7cEBAQAAAIIg/6/uSEABAADuBgUAAAEVp4M/AAAAAElFTkSuQmCC" | base64 -d > src-tauri/icons/32x32.png
          fi
          ls -la src-tauri/icons/

      # Verify the icon exists and has content
      - name: Verify icon
        run: |
          echo "Icon directory contents:"
          ls -la src-tauri/icons/
          echo "Icon file size:"
          stat src-tauri/icons/32x32.png || ls -l src-tauri/icons/32x32.png

      # Continue with the build...

      - uses: tauri-apps/tauri-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
