name: 'publish'

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          #- platform: 'macos-latest'
          #  args: '--target x86_64-apple-darwin'
          #- platform: 'ubuntu-22.04'
          #  args: ''
          #- platform: 'windows-latest'
          #  args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: npm ci --force

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Clean Cargo cache
        run: |
          rm -f src-tauri/Cargo.lock
          rm -rf src-tauri/target

      # Start fresh by removing the entire src-tauri directory
      - name: Clean src-tauri
        run: rm -rf src-tauri

      # Create new directory structure
      - name: Create directory structure
        run: mkdir -p src-tauri/src src-tauri/icons

      # Create Cargo.toml
      - name: Create Cargo.toml
        run: |
          cat > src-tauri/Cargo.toml << 'EOF'
          [package]
          name = "sv1"
          version = "0.1.0"
          description = "A Tauri App"
          authors = ["you"]
          license = ""
          repository = ""
          default-run = "sv1"
          edition = "2021"
          rust-version = "1.60"
          build = "build.rs"

          [build-dependencies]
          tauri-build = { version = "2.0.0-rc.13", features = [] }

          [dependencies]
          serde_json = "1.0"
          serde = { version = "1.0", features = ["derive"] }
          tauri = { version = "2.0.0-rc.13" }

          [features]
          custom-protocol = [ "tauri/custom-protocol" ]
          EOF

      # Create build.rs
      - name: Create build.rs
        run: |
          cat > src-tauri/build.rs << 'EOF'
          fn main() {
            tauri_build::build()
          }
          EOF

      # Create main.rs
      - name: Create main.rs
        run: |
          cat > src-tauri/src/main.rs << 'EOF'
          #![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

          fn main() {
            tauri::Builder::default()
              .run(tauri::generate_context!())
              .expect("error while running tauri application");
          }
          EOF

      # Install Pillow with the necessary flag
      - name: Install Pillow
        run: python3 -m pip install --break-system-packages Pillow

      # Then create the icon
      - name: Create icon
        run: |
          mkdir -p src-tauri/icons
          python3 -c '
          from PIL import Image
          import os
          
          # Create a new 32x32 black image with alpha channel
          img = Image.new("RGBA", (32, 32), (0, 0, 0, 255))
          
          # Ensure the directory exists
          os.makedirs("src-tauri/icons", exist_ok=True)
          
          # Save as PNG with alpha channel
          img.save("src-tauri/icons/32x32.png", "PNG")
          '

      # Verify the icon
      - name: Verify icon
        run: |
          ls -la src-tauri/icons/32x32.png
          file src-tauri/icons/32x32.png

      # Create tauri.conf.json
      - name: Create tauri.conf.json
        run: |
          cat > src-tauri/tauri.conf.json << 'EOF'
          {
            "$schema": "https://raw.githubusercontent.com/tauri-apps/tauri/dev/tooling/cli/schema.json",
            "identifier": "com.example.sv1",
            "productName": "sv1",
            "version": "0.1.0",
            "build": {
              "beforeBuildCommand": "",
              "beforeDevCommand": "",
              "frontendDist": "../build"
            },
            "app": {
              "windows": [
                {
                  "fullscreen": false,
                  "height": 600,
                  "resizable": true,
                  "title": "sv1",
                  "width": 800
                }
              ],
              "security": {
                "csp": null
              }
            },
            "bundle": {
              "active": true,
              "icon": ["icons/32x32.png"],
              "category": "DeveloperTool",
              "copyright": "",
              "macOS": {
                "entitlements": null,
                "exceptionDomain": "",
                "frameworks": [],
                "providerShortName": null,
                "signingIdentity": null
              }
            }
          }
          EOF

      # Install frontend dependencies and build the app
      - name: Install and build frontend
        run: |
          npm ci --force
          npm run build
          ls -la dist  # Verify the build output

      # Create tauri.conf.json with correct frontendDist
      - name: Create tauri.conf.json
        run: |
          cat > src-tauri/tauri.conf.json << 'EOF'
          {
            "$schema": "https://raw.githubusercontent.com/tauri-apps/tauri/dev/tooling/cli/schema.json",
            "identifier": "com.tauri.dev",
            "productName": "sv1",
            "version": "0.1.0",
            "build": {
              "beforeBuildCommand": "npm run build",
              "beforeDevCommand": "npm run dev",
              "frontendDist": "../dist"  # Changed from "../build" to "../dist"
            },
            "app": {
              "windows": [
                {
                  "fullscreen": false,
                  "height": 600,
                  "resizable": true,
                  "title": "sv1",
                  "width": 800
                }
              ],
              "security": {
                "csp": null
              }
            },
            "bundle": {
              "active": true,
              "icon": [
                "icons/32x32.png",
                "icons/128x128.png",
                "icons/128x128@2x.png",
                "icons/icon.icns",
                "icons/icon.ico"
              ],
              "category": "DeveloperTool",
              "copyright": "",
              "macOS": {
                "entitlements": {
                  "com.apple.security.cs.allow-jit": true,
                  "com.apple.security.cs.allow-unsigned-executable-memory": true,
                  "com.apple.security.cs.disable-library-validation": true,
                  "com.apple.security.cs.allow-dyld-environment-variables": true,
                  "com.apple.security.get-task-allow": true
                },
                "exceptionDomain": "",
                "frameworks": [],
                "providerShortName": null,
                "signingIdentity": null
              }
            }
          }
          EOF

      # ... continue with build steps ...

      - uses: tauri-apps/tauri-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      # Clean up any existing files
      - name: Clean Rust files
        run: |
          rm -rf src-tauri/src
          rm -f src-tauri/Cargo.lock
          rm -rf src-tauri/target

      # Create main.rs with absolutely minimal configuration
      - name: Create main.rs
        shell: bash
        run: |
          mkdir -p src-tauri/src
          cat > src-tauri/src/main.rs << 'EOF'
          #![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

          fn main() {
            tauri::Builder::default()
              .run(tauri::generate_context!())
              .expect("error while running tauri application");
          }
          EOF

      # Verify the content of main.rs
      - name: Verify main.rs content
        run: cat src-tauri/src/main.rs
