name: 'publish'

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: npm ci

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Clean Cargo cache
        run: |
          rm -f src-tauri/Cargo.lock
          rm -rf src-tauri/target

      - name: Create or update Cargo.toml
        run: |
          mkdir -p src-tauri
          cat << EOF > src-tauri/Cargo.toml
          [package]
          name = "sv1"
          version = "0.1.0"
          description = "A Tauri App"
          authors = ["you"]
          license = ""
          repository = ""
          default-run = "sv1"
          edition = "2021"
          rust-version = "1.60"
          build = "build.rs"

          [build-dependencies]
          tauri-build = { version = "2.0.0-rc.13", features = [] }

          [dependencies]
          serde_json = "1.0"
          serde = { version = "1.0", features = ["derive"] }
          tauri = { version = "2.0.0-rc.13" }

          [features]
          custom-protocol = [ "tauri/custom-protocol" ]
          EOF

      - name: Create build.rs
        run: |
          cat << EOF > src-tauri/build.rs
          fn main() {
            tauri_build::build()
          }
          EOF

      # Create the icon first, before any Tauri setup
      - name: Create icon directory and file
        shell: bash
        run: |
          mkdir -p src-tauri/icons
          echo 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAB5SURBVFhH7ZBBCsAwCAT9/6fTQ8GTYLKr0BZ6GAIZNaOH9q4557xaa4mI9N77OI7DzFJKKdd1pZRyPxw5Zy2llNZaEhFprWXvfR9+BzAz3vtfQFVRAf8IqCoq4B8BVUUFqCoqQFVRAaqKClBVVICqogJUFRVQVXwD8AYrnifzVVwR3gAAAABJRU5ErkJggg==' | base64 -d > src-tauri/icons/32x32.png
          ls -la src-tauri/icons/32x32.png
          file src-tauri/icons/32x32.png

      # Create a minimal tauri.conf.json
      - name: Create tauri.conf.json
        shell: bash
        run: |
          cat > src-tauri/tauri.conf.json << 'EOF'
          {
            "$schema": "https://raw.githubusercontent.com/tauri-apps/tauri/dev/tooling/cli/schema.json",
            "identifier": "com.tauri.dev",
            "productName": "sv1",
            "version": "0.1.0",
            "build": {
              "beforeBuildCommand": "",
              "beforeDevCommand": "",
              "frontendDist": "../build"
            },
            "app": {
              "windows": [
                {
                  "fullscreen": false,
                  "height": 600,
                  "resizable": true,
                  "title": "sv1",
                  "width": 800
                }
              ],
              "security": {
                "csp": null
              }
            },
            "bundle": {
              "active": true,
              "icon": ["icons/32x32.png"],
              "targets": ["app", "dmg", "updater"]
            }
          }
          EOF

      - name: Create main.rs
        shell: bash
        run: |
          mkdir -p src-tauri/src
          cat > src-tauri/src/main.rs << 'EOF'
          #![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

          fn main() {
            tauri::Builder::default()
              .run(tauri::generate_context!())
              .expect("error while running tauri application");
          }
          EOF

      - name: Verify files
        shell: bash
        run: |
          echo "Icon exists:"
          ls -la src-tauri/icons/32x32.png
          echo "Icon file type:"
          file src-tauri/icons/32x32.png
          echo "Tauri config exists:"
          ls -la src-tauri/tauri.conf.json
          echo "Main.rs exists:"
          ls -la src-tauri/src/main.rs
          echo "Directory structure:"
          tree src-tauri || ls -R src-tauri

      # ... continue with build steps ...

      - uses: tauri-apps/tauri-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
