name: 'publish'

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: npm ci

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Clean Cargo cache
        run: |
          rm -f src-tauri/Cargo.lock
          rm -rf src-tauri/target

      - name: Create or update Cargo.toml
        run: |
          mkdir -p src-tauri
          cat << EOF > src-tauri/Cargo.toml
          [package]
          name = "sv1"
          version = "0.1.0"
          description = "A Tauri App"
          authors = ["you"]
          license = ""
          repository = ""
          default-run = "sv1"
          edition = "2021"
          rust-version = "1.60"
          build = "build.rs"

          [build-dependencies]
          tauri-build = { version = "2.0.0-rc.13", features = [] }

          [dependencies]
          serde_json = "1.0"
          serde = { version = "1.0", features = ["derive"] }
          tauri = { version = "2.0.0-rc.13" }

          [features]
          custom-protocol = [ "tauri/custom-protocol" ]
          EOF

      - name: Create build.rs
        run: |
          cat << EOF > src-tauri/build.rs
          fn main() {
            tauri_build::build()
          }
          EOF

      - name: Create main.rs
        run: |
          mkdir -p src-tauri/src
          cat << EOF > src-tauri/src/main.rs
          // Prevents additional console window on Windows in release
          #![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

          use tauri::Manager;

          fn main() {
            tauri::Builder::default()
              .run(tauri::generate_context!())
              .expect("error while running tauri application");
          }
          EOF

      - name: Display Cargo.toml contents
        run: cat src-tauri/Cargo.toml

      - name: Verify Tauri config
        run: |
          if [ ! -f "src-tauri/tauri.conf.json" ]; then
            echo "Error: src-tauri/tauri.conf.json not found"
            exit 1
          fi
          cat src-tauri/tauri.conf.json

      - name: Build the project
        run: npm run build

      - name: Build Tauri App
        run: npm run tauri build -- ${{ matrix.args }}

      - name: Install ImageMagick (for ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        run: sudo apt-get install -y imagemagick

      - name: Install ImageMagick (for macOS)
        if: matrix.platform == 'macos-latest'
        run: brew install imagemagick

      - name: Install ImageMagick (for Windows)
        if: matrix.platform == 'windows-latest'
        run: choco install imagemagick.app

      - name: Create icons directory and files
        run: |
          mkdir -p src-tauri/icons
          convert -size 32x32 xc:black src-tauri/icons/32x32.png
          convert -size 128x128 xc:black src-tauri/icons/128x128.png
          convert -size 128x128 xc:black src-tauri/icons/icon.png
          convert src-tauri/icons/icon.png src-tauri/icons/icon.ico
          convert src-tauri/icons/icon.png src-tauri/icons/icon.icns
          ls -la src-tauri/icons/

      - name: Create tauri.conf.json
        run: |
          cat << EOF > src-tauri/tauri.conf.json
          {
            "build": {
              "beforeBuildCommand": "",
              "beforeDevCommand": "",
              "devPath": "../dist",
              "distDir": "../dist"
            },
            "package": {
              "productName": "sv1",
              "version": "0.1.0"
            },
            "tauri": {
              "bundle": {
                "active": true,
                "category": "DeveloperTool",
                "copyright": "",
                "deb": {
                  "depends": []
                },
                "externalBin": [],
                "icon": [
                  "icons/32x32.png",
                  "icons/128x128.png",
                  "icons/icon.png"
                ],
                "identifier": "com.tauri.dev",
                "longDescription": "",
                "macOS": {
                  "entitlements": null,
                  "exceptionDomain": "",
                  "frameworks": [],
                  "providerShortName": null,
                  "signingIdentity": null
                },
                "resources": [],
                "shortDescription": "",
                "targets": "all",
                "windows": {
                  "certificateThumbprint": null,
                  "digestAlgorithm": "sha256",
                  "timestampUrl": ""
                }
              },
              "security": {
                "csp": null
              },
              "updater": {
                "active": false
              },
              "windows": [
                {
                  "fullscreen": false,
                  "height": 600,
                  "resizable": true,
                  "title": "sv1",
                  "width": 800
                }
              ]
            }
          }
          EOF

      - uses: tauri-apps/tauri-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
